services:

  api-server:
    container_name: api-server
    build: ./api-server
    ports:
      - "5047:8080"
    volumes:
      - api-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=data/app.db
      - Osu__ClientSecret=${OSU_CLIENT_SECRET}
      - Jwt__SecretKey=${JWT_SECRET_KEY}

  web:
    container_name: web
    build:
      context: ./web
      args:
        REACT_APP_API_URL: http://api-server:8080
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OSU_REDIRECT_URI=http://localhost:3000/
    depends_on:
      - api-server

  discord-bot:
    container_name: discord-bot
    build: ./discord-bot
    env_file: ./discord-bot/.env
    depends_on:
      - api-server

volumes:
  api-data:
